### PR TITLE
Added function getCameraCharacteristics

### PR DESCRIPTION
**Pull request by millecker**
Add the method `getCameraCharacteristics(cb, [errorCallback])`, which returns a JSON object representing the characteristics of all available cameras.

For example:
```
{"CAMERA_CHARACTERISTICS": [
{"INFO_SUPPORTED_HARDWARE_LEVEL":1,"LENS_FACING":1,"SENSOR_INFO_PHYSICAL_SIZE_WIDTH":5.644999980926514,"SENSOR_INFO_PHYSICAL_SIZE_HEIGHT":4.434999942779541,"SENSOR_INFO_PIXEL_ARRAY_SIZE_WIDTH":4032,"SENSOR_INFO_PIXEL_ARRAY_SIZE_HEIGHT":3024,"LENS_INFO_AVAILABLE_FOCAL_LENGTHS":[{"FOCAL_LENGTH":4.199999809265137}]},
{"INFO_SUPPORTED_HARDWARE_LEVEL":0,"LENS_FACING":0,"SENSOR_INFO_PHYSICAL_SIZE_WIDTH":3.494999885559082,"SENSOR_INFO_PHYSICAL_SIZE_HEIGHT":2.625999927520752,"SENSOR_INFO_PIXEL_ARRAY_SIZE_WIDTH":2608,"SENSOR_INFO_PIXEL_ARRAY_SIZE_HEIGHT":1960,"LENS_INFO_AVAILABLE_FOCAL_LENGTHS":[{"FOCAL_LENGTH":2.0999999046325684}]}
]}
```

### CODE REVIEW

**Comment by westonganger** [comment]
I dont see the point in adding this method what are you trying to find out?

**Comment by millecker** [comment]
I'm trying to find out the **focal length** and **sensor height** of the camera to calculate the distance of an object. e.g., Distance to Object = real object height x focal length / object height on sensor

**Comment by danhab99** [comment]
I could actually use this, thank you :smile:

**Comment by johnroper100** [comment]
I could use this as well.

**Comment by StarStep** [comment]
Would be nice!

**Comment by westonganger** [comment]
Okay i'm interested in this PR. Can you add this to iOS as well?

**Comment by westonganger** [comment]
This is now merged to master bb82ece

**Pull request closed without merging**
