### PR TITLE
Added focus auto mode, use of zoom, use of flash, and set of previewS…

### PR DESCRIPTION
**Pull request by julitroalves**
I have added some control of some resources of android camera plugin such as set zoom, set flash mode and preview size.

### CODE REVIEW

**Comment by erperejildo** [comment]
Could you provide some info to how to use zoom and flash?
Also, I've tried the auto focus. It works well if you wait to see the image correctly before you take the picture but if you don't wait and take the picture before focus, the camera do the focus first and takes the picture after this, which it's ok (even this picture before loading symbol looks ok) but the picture when loads, loads with blur.

**Comment by julitroalves** [comment]
To use zoom camera resource you would to call `cordova.plugins.camerapreview.setZoom(value)` and add zoom value on function parameter.

To use flash camera resource you would to call `cordova.plugins.camerapreview.setFlashMode(value)` and add flash int mode what are following: 
 0 -> OFF
 1 -> ON
 2 -> TORCH
 3 -> AUTO

About the issue with blur loaded picture I will verify this later and return here.

**Comment by pablobianchi** [comment]
Hi, i just update the 3 files but i can not get the flash to work, i am using cordova.plugins.camerapreview.setFlashMode(1); , but nothing happens, is there something else ? i m using Android 5.0.2

Thanks

**Comment by julitroalves** [comment]
You have sure that your camera device have suport to this flash? For example I have a camera that no have support for ON Flash (Mode 1) just suports AUTO FLASH (mode 3).

tip: Try to see whats happens on `adb logcat`.

**Comment by pablobianchi** [comment]
Hi, after some tries i get it working, the flash mode is 2 and i am setting it with a timeout of a second after i start the camera. 

Thanks !

**Comment by piyushdutta** [comment]
I tried it with timeout it didnt work for me. After the .onStart camera i gave settimeout function and called the camerapreview.setFlash(2) but it didnt work. It gave me a error that it didnt recognize the setFlash function and same for the setZoom function. How did you do it @pablobianchi

**Comment by KarinW** [comment]
Hi, 
does this work for iOS as well?
Plus how do I know which is the highest zoom value to set in cordova.plugins.camerapreview.setZoom(value)?

**Comment by piyushdutta** [comment]
Hi @KarinW yes it does work for IOS too but i would suggest trying out [this](https://github.com/apache/cordova-plugin-camera) camera popover options for ios.
As for your resolution and zoom value that you will have test and adjust accordingly what suits best for you.

**Comment by JimPee** [comment]
How can i add this version of the plugin to my project? this looks awesome

**Comment by erperejildo** [comment]
These changes have been merged with this PR:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/159

**Comment by erperejildo** [comment]
@JimPee update with the new version of master, these changes are already on it.
In fact, we could cancel this PR

**Pull request closed without merging**
