### PR TITLE
Old devices support

### PR DESCRIPTION
**Pull request by bvx89**
Added support library for using the exifinterface on older Android devices.

Without this, the camera will crash when trying to check the exif tags of the image data.

### CODE REVIEW

**Comment by westonganger** [comment]
I like this PR. I would like to request one change. Please rename onBackButtonTapped to onBackButton

**Comment by bvx89** [comment]
I've renamed the function now. Should I just close the other PR?

**Comment by rasaturyan** [comment]
Please also change function name in the README file too. Thanks for this PR.

**Comment by bvx89** [comment]
Woops, forgot that one. Thanks for notifying. Pushed the change now.

**Comment by westonganger** [comment]
Merged. Thanks for your contribution!

**Comment by kdomagoj** [comment]
Can you please check #373 ?
App crashes on back button , cordova backbutton event is not being call.
When revert to npm release 0.9.0 everything works ok.

Thanks.

**Pull request merged**
