### PR TITLE
Added function getSupportedColorEffects

### PR DESCRIPTION
**Pull request by rafaelbecks**
Only Android support. Added function to get supported color effects because I had issues testing in many devices. If the pull request is accepted, I cand add the documentation section in README

### CODE REVIEW

**Comment by westonganger** [comment]
Thanks looks good. Please add documentation before I merge.

**Comment by rafaelbecks** [comment]
@westonganger thanks for  quick reply! I've just added the documentation

**Comment by westonganger** [comment]
It doesn't state anywhere that it's for Android only. Please make this clear.

**Comment by rafaelbecks** [comment]
Ok. I'll do the change. I also have just seen something else. The `setColorEffect` funcion needs a minor change, it compares the input string with the camera parameters constants, there is not need of verify if the color effect is supported (only if is set with the array returned on `getSupportedColorEffects`), besides, If I set a color effect unavabilable in the constants, it will return "color effect not supported" when indeed it's supported. I'll make the change and I'll let you know you when is done

**Comment by rafaelbecks** [comment]
@westonganger it's done. I fix the documentation and I made the improve in `setColorEffect`.

**Comment by westonganger** [comment]
Merged! Thanks for your contribution.

**Pull request merged**
